menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/tuzkiss
    GitHub: https://github.com/tuzkiss
    Resume: /resume.html

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:


# Copyright Infomation
startyear: 2015
