menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/tuzkiss
    GitHub: https://github.com/tuzkiss
    Resume: http://www.tuzkiss.com/resume/
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:


# Copyright Infomation
startyear: 2015
