menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/tuzkiss
    GitHub: https://github.com/tuzkiss
    Resume: /resume.html

favicon: /favicon.ico
logo: /favicon.png

# Comment
# e.g disqus: tuzkiss
disqus: tuzkiss
duoshuo:


# Copyright Infomation
startyear: 2015
